### ISSUE TITLE
md文件名有特殊符号会导致异常

### ISSUE THREAD

**Issue by CtrlAltDelet** [YellowAndGreen/Md-ImgLocalize#11]
我有一个文件名是[abc]1234.md  在转换时会将文件名的方括号当做md语言的特殊符号导致异常

**Comment by YellowAndGreen** [comment]
你好，我在使用了一个markdown并将其命名为`[abc]1234.md`以进行测试，同时在该文件中也加入了`[abc]1234.md`，但没有复现出异常情况。可以详细说说你的具体情况（文件名，文件位置等），以及提供异常错误代码吗？

**Comment by CtrlAltDelet** [comment]
文件转换是正常的，也没有报错，但是这样是无法被客户端正常解析查看的（使用的vscode的md预览功能）
经过测试，文件名中如果出现空格等特殊符号也会导致，建议加入replace将md文件名中的特殊符号去除，ths

**Comment by YellowAndGreen** [comment]
抱歉哈，我没法复现您的问题，我也是使用vscode测试的：
![Preview  abc 1234 md - Md-ImgLocalize  WSL_ Ubuntu-22 04  - Visual Studio Code 2024_1_11 21_34_14](https://github.com/YellowAndGreen/Md-ImgLocalize/assets/33193090/7d24fe96-3c18-4ab1-b481-f259f1e7c44d)

**Comment by CtrlAltDelet** [comment]
[[hhh gan]  hh666 csdne255a0a883bf25b3.md](https://github.com/YellowAndGreen/Md-ImgLocalize/files/13906970/hhh.gan.hh666.csdne255a0a883bf25b3.md)
谢谢 难道是因为我用的自带的预览有问题
<img width="1177" alt="image" src="https://github.com/YellowAndGreen/Md-ImgLocalize/assets/38282439/91f50913-7f27-47bd-a630-ffae78f66c20">
