### ISSUE TITLE
很好用，希望可以支持一下html语法的图片下载

### ISSUE THREAD

**Issue by hunShiPig** [YellowAndGreen/Md-ImgLocalize#3]

**Comment by YellowAndGreen** [comment]
指的是img标签吗？可以提供具体的例子吗？

**Comment by hunShiPig** [comment]
> 指的是img标签吗？可以提供具体的例子吗？

对的，有的博客用img标签自定义了图片的格式。
例如：` <img src="https://seazean.oss-cn-beijing.aliyuncs.com/img/Java/Debug条件断点.png" alt="Debug条件断点" style="zoom:50%;" /> `

**Comment by YellowAndGreen** [comment]
已添加对img标签的支持。

**Comment by hunShiPig** [comment]
> 已添加对img标签的支持。

正则表达式貌似出现了一些问题， 现在`[ ]`也会被替换，而不是`![]`：
原文是这样的：
```
[点击链接下载xpath](https://pan.baidu.com/s/1_oVX5pUJO5L5ff6uXPCTsw%C2%A0 "点击链接下载xpath")
```

打印输出：
```
replaced: https://pan.baidu.com/s/1_oVX5pUJO5L5ff6uXPCTsw%C2%A0 "点击链接下载xpath"
with python爬虫基础.assets\4Bcb1793A81_oVX5pUJO5L5ff6uXPCTsw%C2%A0 "点击链接下载xpath"
 on file python爬虫基础.md
```

**Comment by YellowAndGreen** [comment]
> > 已添加对img标签的支持。
> 
> 正则表达式貌似出现了一些问题， 现在`[ ]`也会被替换，而不是`![]`：
> 原文是这样的：
> ```
> [点击链接下载xpath](https://pan.baidu.com/s/1_oVX5pUJO5L5ff6uXPCTsw%C2%A0 "点击链接下载xpath")
> ```
> 
> 打印输出：
> ```
> replaced: https://pan.baidu.com/s/1_oVX5pUJO5L5ff6uXPCTsw%C2%A0 "点击链接下载xpath"
> with python爬虫基础.assets\4Bcb1793A81_oVX5pUJO5L5ff6uXPCTsw%C2%A0 "点击链接下载xpath"
>  on file python爬虫基础.md
> ```

好的，已经修复了。

**Comment by hunShiPig** [comment]
> > > 已添加对img标签的支持。
> > 
> > 
> > 正则表达式貌似出现了一些问题， 现在`[ ]`也会被替换，而不是`![]`：
> > 原文是这样的：
> > ```
> > [点击链接下载xpath](https://pan.baidu.com/s/1_oVX5pUJO5L5ff6uXPCTsw%C2%A0 "点击链接下载xpath")
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 打印输出：
> > ```
> > replaced: https://pan.baidu.com/s/1_oVX5pUJO5L5ff6uXPCTsw%C2%A0 "点击链接下载xpath"
> > with python爬虫基础.assets\4Bcb1793A81_oVX5pUJO5L5ff6uXPCTsw%C2%A0 "点击链接下载xpath"
> >  on file python爬虫基础.md
> > ```
> 
> 好的，已经修复了。

👍可以了
