### ISSUE TITLE
On Linux  Md-ImgLocalize  creates MDPATH\Test.md

### ISSUE THREAD

**Issue by johnblommers** [YellowAndGreen/Md-ImgLocalize#4]
Given a directory called `MDPATH` that contains `Test.md`

After invoking `python3 main.py --md_path ~/Desktop/MDPATH  --modify_source`

the program does not modify `Test.md`

Instead it creates a file `MDPATH\Test.md`  alongside directory `MDPATH` rather than modifying `Test.md` inside the folder.

This looks like it's caused by a programming error. On Linux the forward slash `/` is the proper way to separate a directory from a filename. In this case the program is using `\` which is very Windows-esque.

**Comment by YellowAndGreen** [comment]
I'll solve this bug, thanks.

**Comment by YellowAndGreen** [comment]
Fixed, thanks a lot.

**Comment by johnblommers** [comment]
After doing a `git pull` in the `Md-ImgLocalize` directory and retesting I can confirm that this issue is resolved - with thanks! 

Let me therefore close this out.
