### ISSUE TITLE
对特殊的图片地址如何解决

### ISSUE THREAD

**Issue by jinshuqishi2019** [YellowAndGreen/Md-ImgLocalize#5]
使用现有程序难以对下面这种图片地址进行本地化下载，请问如何做才能适配，谢谢。
```
https://cubox.pro/c/filters:no_upscale()?imageUrl=https%3A%2F%2Fimg.laoda.de%2Fi%2F2022%2F03%2F31%2Fhi43i6_7.webp&valid=true
```

**Comment by YellowAndGreen** [comment]
该链接中的图片url实际不存在：`https%3A%2F%2Fimg.laoda.de%2Fi%2F2022%2F03%2F31%2Fhi43i6_7.webp`，所以重新跳转到了新的链接。
本代码中的下载方法不支持跳转链接的图片下载，所以我暂时没有好的解决方法。
