### ISSUE TITLE
请问能否做成vscode插件哈

### ISSUE THREAD

**Issue by wanzhiyu** [YellowAndGreen/Md-ImgLocalize#6]
谢谢大佬，只是一个提议

**Comment by YellowAndGreen** [comment]
当然可以，正在考虑可行性以及改造方案。

**Comment by YellowAndGreen** [comment]
找到了一个已有的[vscode插件](https://github.com/pattazl/markdown-image-manage)实现了此功能，本仓库代码就不改成插件形式了。

**Comment by wanzhiyu** [comment]
谢谢，确实已经有了，感谢！
